### ISSUE TITLE
Installation error with latest (1.7.2) in R 4.0.1: ERROR: unable to collate and parse R files for package ‘tidySingleCellExperiment’

### ISSUE THREAD

**Issue by mattgalbraith** [stemangiola/tidySingleCellExperiment#43]
> devtools::install_github("stemangiola/tidySingleCellExperiment")
Downloading GitHub repo stemangiola/tidySingleCellExperiment@HEAD
✔  checking for file ‘/tmp/RtmpKpe7AU/remotes4c012bf2b/stemangiola-tidySingleCellExperiment-27335c1/DESCRIPTION’ (502ms)
─  preparing ‘tidySingleCellExperiment’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘tidySingleCellExperiment’ ...
   ** using staged installation
   ** R
   Error in parse(outFile) : 
     /tmp/Rtmp2rFGO3/Rbuild4c363d10ffec/tidySingleCellExperiment/R/print_method.R:39:27: unexpected '>'
   38: 
   39:   number_of_features = x |>
                                 ^
   ERROR: unable to collate and parse R files for package ‘tidySingleCellExperiment’
─  removing ‘/tmp/Rtmp2rFGO3/Rinst4c364825a588/tidySingleCellExperiment’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'tidySingleCellExperiment' from GitHub:
  ! System command 'R' failed

**Comment by mattgalbraith** [comment]
Installing older version works:
devtools::install_github("stemangiola/tidySingleCellExperiment@v1.3.2")
Downloading GitHub repo stemangiola/tidySingleCellExperiment@v1.3.2
✔  checking for file ‘/tmp/RtmpKpe7AU/remotes4c015fda7b/stemangiola-tidySingleCellExperiment-9ea3777/DESCRIPTION’ (515ms)
─  preparing ‘tidySingleCellExperiment’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
─  checking for LF line-endings in source and make files and shell scripts (53.5s)
─  checking for empty or unneeded directories
─  building ‘tidySingleCellExperiment_1.3.2.tar.gz’
   
* installing *source* package ‘tidySingleCellExperiment’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (tidySingleCellExperiment)

**Comment by mblue9** [comment]
Thanks for the error report @mattgalbraith, I've submitted a PR [here](https://github.com/stemangiola/tidySingleCellExperiment/pull/44) to fix that.  The R version needs to be >=4.1 for tidySingleCellExperiment v1.7.2 as it makes use of the base R pipe `|>` introduced R 4.1.
