### ISSUE TITLE
options("restore_SingleCellExperiment_show" = FALSE)` doesn't work?

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidySingleCellExperiment#45]
It looks like `options("restore_SingleCellExperiment_show" = FALSE)` doesn't work to revert back to tidy view?

See the workshop here https://tidytranscriptomics-workshops.github.io/bioc2022_tidytranscriptomics/articles/tidytranscriptomics_case_study.html#introduction-to-tidysinglecellexperiment

It worked fine with tidySummarizedExperiment here https://saskiafreytag.github.io/biocommons-r-intro/60-next-steps/index.html

**Comment by stemangiola** [comment]
Fixed in version 1.7.4

**Comment by mblue9** [comment]
Great, can you make a release v1.7.4 then I can add it to the workshop?

**Comment by stemangiola** [comment]
done here https://github.com/stemangiola/tidySingleCellExperiment/releases/tag/v1.7.4
