### ISSUE TITLE
README has an incredibly long assay(pbmc_small_tidy)

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidySingleCellExperiment#49]
Hello @mblue9,  sorry I merged without double-checking. The README has an incredibly long assay(pbmc_small_tidy), have a look :)

**Comment by mblue9** [comment]
Ah that was copied from the Introduction which also has that long assay. Have suggested a fix here https://github.com/stemangiola/tidySingleCellExperiment/pull/50

**Comment by stemangiola** [comment]
Thanks!
