### ISSUE TITLE
Repo website link is broken

### ISSUE THREAD

**Issue by multimeric** [stemangiola/tidySingleCellExperiment#61]
The repo's website is a broken link:

![image](https://user-images.githubusercontent.com/5019367/233267016-16be6c9a-63be-445b-92c2-bfbd335c894c.png)

Points to https://stemangiola.github.io/tidySCE/articles/introduction.html instead of https://stemangiola.github.io/tidySingleCellExperiment/index.html

**Comment by stemangiola** [comment]
@william-hutchison could you take care of this?

**Comment by multimeric** [comment]
Worth mentioning that only the repo's owner can fix this.

**Comment by stemangiola** [comment]
I see, is in settings. I will take care of this. thanks.
