### ISSUE TITLE
Consider adding summarize.SingleCellExperiment as an explicit alias of summarise.SingleCellExperiment

### ISSUE THREAD

**Issue by keyes-timothy** [stemangiola/tidySingleCellExperiment#62]
This is a very small bauble, but see the following issue: 

``` r
suppressMessages(library(tidySingleCellExperiment))

pbmc_small |>
  summarise(nCount_RNA = mean(nCount_RNA))
#> tidySingleCellExperiment says: A data frame is returned for independent data analysis.
#> # A tibble: 1 × 1
#>   nCount_RNA
#>        <dbl>
#> 1       245.

pbmc_small |> 
  summarize(nCount_RNA = mean(nCount_RNA))
#> Error in summarize(pbmc_small, nCount_RNA = mean(nCount_RNA)): could not find function "summarize"
```

<sup>Created on 2023-06-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

What I mean to show here is that, when `dplyr` is not attached, you can run into some namespace issues with summarise vs. summarize method deployment for `SingleCellExperiment`'s

<sup>Created on 2023-06-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by stemangiola** [comment]
Good point, @william-hutchison please see how dplyr does it.
