### ISSUE TITLE
adapt aggregate_features() to tidyseurat which is based on ttservice

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidySingleCellExperiment#63]
@william-hutchison aggregate_cells() in tidyseurat relies on the generic method in ttservice, could you please adapt this method to tidyseurat, so they can be used together if both tidyseurat and tidySCE are loaded at the same time?

https://github.com/stemangiola/tidyseurat/pull/61

It is just few lines of code to be modified in the methods

**Comment by stemangiola** [comment]
Hello @william-hutchison would you have time today to make this pull request?

**Comment by william-hutchison** [comment]
Hi @stemangiola, sure I will start working on this now

**Comment by stemangiola** [comment]
@william-hutchison for reference,  When you are doing a pull request related to an issue you should link them with the menu on the right.
