### ISSUE TITLE
Method for S4 DataFrame for left_join

### ISSUE THREAD

**Issue by lambdamoses** [stemangiola/tidySingleCellExperiment#80]
This way we can use `colData(sce)` in left join into another SCE object without having to convert to S3 tibble.

**Comment by stemangiola** [comment]
Do you have in mind (?)

`single_cell_experiment |> *_join(DataFrame)`

It sounds good!

**Comment by stemangiola** [comment]
Sure,

we would need all join flavours (full, right, left, anti), as tidySingleCellExperiment has API for all of them. But it should be pretty straightforward.

**Comment by lambdamoses** [comment]
Do you want me to do a pull request? I think it should be pretty easy to implement, though I won't be able to do it soon because I'm busy with many other things recently.

**Comment by stemangiola** [comment]
> Do you want me to do a pull request? I think it should be pretty easy to implement, though I won't be able to do it soon because I'm busy with many other things recently.

That would be great.

**Comment by lambdamoses** [comment]
OK, super last minute for Bioc 3.18. Question: It seems that the code in those different flavors of `*_join` is all the same except for the `dplyr` function called. Do you want me to refactor using a function factory, so if you want to change the `*_join` functions, then you only need to change 1 place instead of 4 places?

**Comment by lambdamoses** [comment]
Yes, it takes all arguments of `*_join`. The outer function controls the small parts that differ among the 4 join flavors, while the inner function implements the large part that is the same for all flavors of join. The outer function `.join_factory` returns the inner function, which takes all arguments of join.

**Comment by stemangiola** [comment]
the thing that confuses me is that `left_join.SingleCellExperiment` should take all the argument of dplyr left_join. but it does not in your refactored version

**Comment by lambdamoses** [comment]
What do you mean? The original code says, `dplyr::left_join(y, by=by, copy=copy, suffix=suffix, ...)`, and the arguments that show up here and `...` are preserved in `.join_factory`'s inner function. The other arguments are passed through `...`.

**Comment by stemangiola** [comment]
OK, I have never see this kind of declaration

```
left_join.SingleCellExperiment <- my_function()
```

but only

```
left_join.SingleCellExperiment <- my_function
```

how can you do

```
debug(...)
```

for join_functions now?

can you dsinply do

```
debug(left_join)
```

?

**Comment by lambdamoses** [comment]
The RStudio debugger will still work. Keep on pressing "step in", the debugger will bring you to the inner function of the function factory.

**Comment by stemangiola** [comment]
> Yes, it takes all arguments of `*_join`. The outer function controls the small parts that differ among the 4 join flavors, while the inner function implements the large part that is the same for all flavors of join. The outer function `.join_factory` returns the inner function, which takes all arguments of join.
> 
> Since you want S4 DataFrame for y for `tidySE`, do you want the refactored version?

OK feel free to push a PR with the refactoring, I am trusting you on this :) as I don't fully understand this high-level factoring of function makers.

**Comment by lambdamoses** [comment]
> I am trusting you on this :) as I don't fully understand this high-level factoring of function makers.

I ran all the unit tests and wrote new unit tests for allowing S4. This is a type of functional programming. Read more about it here: https://adv-r.hadley.nz/function-factories.html

**Comment by william-hutchison** [comment]
Hi @lambdamoses, thanks for your great contribution. Please add your details to this authorship list if you would like to be included in our upcoming publication:

https://docs.google.com/spreadsheets/d/19XqhN3xAMekCJ-esAolzoWT6fttruSEermjIsrOFcoo/edit?usp=sharing

**Comment by llrs** [comment]
I came here thanks to @mikelove through Bioconductor's slack. 

I want to filter my SCE according to `scutter::addPerFeatureQC`, I found it was not easy to do that:
`sce |> scutter::addPerFeatureQC() |> rowData() |> as.data.frame() |> filter(...)`.
Would some other generics be of interest? I think in something like a package (tidyS4Vectors?) increasing the methods as needed.
