### ISSUE TITLE
Clarification of getting back/disabling the viewing of sce as tibble?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [stemangiola/tidySingleCellExperiment#91]
Hi there, 

Thanks for developing a very useful package. 

Would you mind clarifying how we can disabling ("getting back") the `sce` class of the `sce` object? 

After I installed the package, immediately my sce object becomes a tibble object without me setting or running any function to specify that, which was a bit unexpected.

**Comment by stemangiola** [comment]
with 

```r
options("restore_SingleCellExperiment_show" = TRUE)
```

You can go back to the original visualisation

> immediately my sce object becomes a tibble object

The SCE object is never touched, just its representation changes. Have a look here 

https://tidyomics.github.io/tidyomicsWorkshopBioc2023/articles/tidyGenomicsTranscriptomics.html

@william-hutchison could we add the toggle example in our workshop

https://tidyomics.github.io/tidyomicsWorkshopBioc2023/articles/tidyGenomicsTranscriptomics.html

to the `tidySingleCellExperiment` README and Vignette?

**Comment by william-hutchison** [comment]
Hello @stemangiola and @denvercal1234GitHub. Sure, I think including this information is a great idea. I will add it now
